project:
  type: website
  output-dir: docs
execute:
  freeze: auto
website:
  title: "requal"
  favicon: img/favicon.ico
  navbar:
    logo: img/rql_logo.png
    left:
      - href: get_started.qmd
        text: Getting started
      - href: posts.qmd
        text: Posts
      - href: contact.qmd
        text: Contact
    right:
      - href: https://github.com/RE-QDA/requal/wiki
        icon: book
        target: _blank
      - href: https://github.com/RE-QDA/requal/discussions
        icon: chat-text
        target: _blank
      - href: https://github.com/RE-QDA/requal
        icon: github
        target: _blank
format:
  html:
    theme: morph
    css: styles.css
    toc: true





