project:
  type: website

website:
  title: "requal"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: get_started.qmd
        text: Getting started
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



