project:
  type: website
  output-dir: docs

website:
  title: "requal"
  navbar:
    logo: img/rql_logo.png
    left:
      - href: get_started.qmd
        text: Getting started
      - href: contact.qmd
        text: Contact
      - href: wiki.qmd
        text: Wiki

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



