version: "3.4"

x-service: &service
  restart: always

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: requal_admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: requal
    volumes:
      - ./data:/docker-entrypoint-initdb.d/